#
# This file is part of the ansible-template project and should not be changed
#

---
- hosts: localhost
  gather_facts: yes
  environment:
    AWS_PROFILE: "{{ aws_profile }}"
    AWS_REGION: "{{ aws_region }}"
  roles:
    - default
    - prod
    - infra
