---

# ECS related
# ecs_environment_variables:
#   - name: "MY_ENV_VAR"
#     value: "{{ my_variable }}"
#   - name: "MY_SECOND_VAR"
#     value: "hardcoded"
# ecs_additional_port_mappings:
#   - containerPort: "8080"
#     hostPort: "8080"
