#
# This file is part of the ansible-template project and should not be changed
#
---

# Application port, used by
# - Security groups
# - ELB eventually
application_port: 9000
application_security_group_default_open_ports:
  - port: "{{ application_port }}"
    from: "0.0.0.0/0"
  - port: 22
    from: "0.0.0.0/0"
# The application port and ssh are opened by default, any additional ports can be configured in this list and will be merged.
application_security_group_additional_open_ports: []
# this is is resulting effective group
application_security_group_open_ports: "{{ application_security_group_default_open_ports + application_security_group_additional_open_ports }}"

additional_user_data_bootcmd: |
  - echo "you can add additional bootcommands"
  - echo "by overwriting the variable additional_user_data_bootcmd"

additional_user_data_runcmd: |
  - echo "you can add additional runcommands"
  - echo "by overwriting the variable additional_user_data_runcmd"

additional_ecs_config: |
  # you can add additional env variables by
  # override the ansible variable additional_ecs_config

additional_write_files: |
  - path: /tmp/ansible_additional.txt
    permissions: 0644
    owner: root
    content: |
      Just an example of an additional file to write on boot

additional_cloud_config_commands: ""

additional_python_pip_packages: ""


# ASG Related
asg_subnets: []
asg_min_size: 1
asg_max_size: 1
asg_desired_capacity: 1
asg_additional_tags:
  - Name: "{{ application_name }}"
    propagate_at_launch: yes

asg_override_desired_capacity: false
# This allows additional tags to be set on created instances
# asg_additional_tags: []
#  - Environment: "{{ environment }}"
#    propagate_at_launch: yes


launch_config_instance_size: "t2.small"
launch_config_instance_profile_name: null
launch_config_assign_public_ip: false
