#
# This file is part of the ansible-template project and should not be changed
#
---

# Features that can be enabled or disabled :
create_auto_scaling_group: false
create_ecs_cluster: false
create_ecs_service: false
