#
# This file is part of the ansible-template projet and should not be changed
#
---

- name: Determine ECS ami
  set_fact:
    launch_config_ami: "{{launch_config_ami | default(launch_config_amis_per_region[aws_region])}}"

- debug: msg="Using ECS AMI {{ launch_config_ami }}"

- name: Create inboud traffic rules
  set_fact:
    proto: tcp
    from_port: "{{ item.port | int }}"
    to_port: "{{ item.port | int }}"
    cidr_ip: "{{ item.from }}"
  with_items: "{{ application_security_group_open_ports }}"
  register: _app_security_group_rules_output

- name: Flatten inboud traffic rules
  set_fact:
    _app_security_group_rules: "{{ _app_security_group_rules_output.results | list | map(attribute='ansible_facts') | list }}"

- debug: msg="Using application security group rules {{ _app_security_group_rules }}"

# Creates a target security group in which the autoscaled machine will running
# If the
- name: Application inbound traffic
  ec2_group:
      name: "{{ application_name  }}-app"
      description: Allows traffic into the application server
      vpc_id: "{{ vpc_id }}"
      rules: "{{ _app_security_group_rules }}"
  register: app_security_group

- name: Determine launch config hash
  set_fact:
    launch_config_version: "{{ launch_config_params | hash('sha1') }}"
  vars:
    launch_config_params:
      name: "{{ application_name }}"
      image_id: "{{ launch_config_ami }}"
      key_name: "{{ launch_config_key_name }}"
      region: "{{ aws_region }}"
      security_groups: "{{ [ app_security_group['group_id']] }}"
      instance_type: "{{ launch_config_instance_size }}"
      user_data: "{{ launch_config_user_data }}"
      instance_profile_name: "{{ launch_config_instance_profile_name }}"
      assign_public_ip: "{{ launch_config_assign_public_ip }}"

- name: Launch configuration
  ec2_lc:
    name: "{{ application_name }}_{{ launch_config_version }}" # Important, change this if changing anything else or it WILL NOT come into effect.
    image_id: "{{ launch_config_ami }}"
    key_name: "{{ launch_config_key_name }}"
    region: "{{ aws_region }}"
    security_groups: "{{ [ app_security_group['group_id']] }}"
    instance_type: "{{ launch_config_instance_size }}"
    user_data: "{{ launch_config_user_data }}"
    instance_profile_name: "{{ launch_config_instance_profile_name }}"
    assign_public_ip: "{{ launch_config_assign_public_ip }}"
  register: app_launch_config

- name: create autoscaling group
  ec2_asg:
    name: "{{ app_name }}"
    # load_balancers: "{{ app_name }}"
    launch_config_name: "{{ app_launch_config['name'] }}"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    region: "{{ aws_region }}"
    vpc_zone_identifier: "{{ asg_subnets | join(',') }}"
    health_check_type: EC2
    health_check_period: 300
    tags: "{{ asg_additional_tags }}"
