#
# This file is part of the ansible-template project and should not be changed
#
---

- name: Create resulting task defintion dict
  set_fact:
    _service_with_task_arns: []

- name: Create task definitions defined in services
  include: ecs_task_definitions_for_service.yml service={{ outer }}
  with_items: "{{ ecs_services }}"
  loop_control:
    loop_var: outer


- debug: msg="Fact _service_with_task_arns now is {{ _service_with_task_arns }}"

# - name: Ensure ecs_task_definitions_output is valid
#   set_fact:
#     ecs_task_definitions_output: []
#   when: "{{ ecs_task_definitions_output.skipped is defined }}"
#
# - debug: msg="ecs_task_definitions_output now is {{ ecs_task_definitions_output }}"
