#
# This file is part of the ansible-template projet and should not be changed
#
---

- name: Create ECS task definition
  ecs_taskdefinition:
    region: "{{ aws_region }}"
    containers:
    - name: "{{ item.container_name }}"
      cpu: "{{ item.cpu }}"
      essential: "{{ item.essential }}"
      image:  "{{ item.image }}" # {{ docker_repo }}/{{ app_name }}:{{docker_tag}}
      memory: "{{ item.memory }}"
      environment: "{{ item.environment }}"
      portMappings: "{{ item.portMappings }}"
      links: "{{ item.links}}"
    state: present
    family: "{{ ecs_task_name }}"
    register: "ecs_task_{{ item.container_name }}"
