#
# This file is part of the ansible-template projet and should not be changed
#
---

- name: Create ECS cluster
  ecs_cluster:
    profile: "{{ profile }}"
    name: "{{ ecs_cluster_name }}"
    state: present
    region: "{{ region }}"

- name: Create ECS Service
  ecs_service:
    profile: "{{ profile }}"
    region: "{{ region }}"
    name: "{{ app_name }}"
    cluster: "{{ ecs_cluster_name }}"
    task_definition: "{{ ecs_task_name }}:{{ ecs_task['taskdefinition']['revision'] }}"
    state: present
    desired_count: 1
    role: "cogs-ecs"
    load_balancers:
      - loadBalancerName: "{{ app_name }}"
        containerName: "{{ app_name }}"
        containerPort: 9000
