#
# This file is part of the ansible-template projet and should not be changed
#
---

- name: Create ECS cluster
  ecs_cluster:
    name: "{{ ecs_cluster_name }}" # doesn't use default but instead sets the fact so other tasks can resuse
    state: present
    region: "{{ aws_region }}"
