#
# This file is part of the ansible-template projet and should not be changed
#
---

- name: Create ECS cluster
  ecs_cluster:
    name: "{{ ecs_cluster_name }}"
    state: present
    region: "{{ aws_region }}"
