#
# This file is part of the ansible-template project and should not be changed
#
---

- name: Create ECS Service
  ecs_service:
    name: "{{ item.name }}"
    cluster: "{{ ecs_cluster_name }}"
    task_definition: "{{ item.task.taskDefinitionArn }}" # "{{ ecs_task_name }}:{{ ecs_task['taskdefinition']['revision'] }}"
    state: present
    desired_count: "{{ ecs_service_desired_count | default(asg_desired_capacity) }}"
    #role: "ecsServiceRole"
    #load_balancers: " {{ ecs_service_loadbalancers }}"
      # - loadBalancerName: "{{ app_name }}"
      #   containerName: "{{ app_name }}"
      #   containerPort: 9000
  with_items: "{{ _service_with_task_arns }}"
