#
# This file is part of the ansible-template projet and should not be changed
#
---

- name: Create ECS Service
  ecs_service:
    region: "{{ aws_region }}"
    name: "{{ application_name }}"
    cluster: "{{ ecs_cluster_name }}"
    task_definition: "{{ ecs_task_definition }}" # "{{ ecs_task_name }}:{{ ecs_task['taskdefinition']['revision'] }}"
    state: present
    desired_count: 1
    role: "ecsServiceRole"
    load_balancers: " {{ ecs_service_loadbalancers }}"
      # - loadBalancerName: "{{ app_name }}"
      #   containerName: "{{ app_name }}"
      #   containerPort: 9000
