#
# This file is part of the ansible-template project and should not be changed
#
---

# This is where we include the override, anything from set_default can be overridden here
- include_vars: main.yml

- include_vars:
    dir: 'vars'

# This applies any defaults after reading all vars
- include: set_defaults.yml

# Avoid running on vanilla config, apologies for whoever wants to actually create an environment called my-app.
- fail: msg="Failing to continue with default application name"
  when: application_name == 'my-app'

- include: ec2_elb.yml
  when: create_elb

- include: ec2_autoscaling.yml
  when: create_auto_scaling_group

- include: ecs_cluster.yml

- include: ecs_task_definitions.yml

- include: ecs_service.yml
