#
# This file is part of the ansible-template projet and should not be changed
#
---

# This is done via a set-facts rather then a include_vars because the template update only update tasks, not vars.
# Adding a defaults.yml makes the tasks/vars split more difficult to understand
- include: set_defaults.yml

# This is where we include the override, anything from set_default can be overridden here
- include_vars: main.yml

- include: ec2_autoscaling.yml
  when: "{{ create_auto_scaling_group }}"

- include: ecs_cluster.yml

- include: ecs_task_definitions.yml

- include: ecs_service.yml
